# Source: https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/appengine/standard_python3/building-an-app/building-an-app-1/app.yaml

runtime: python39

# https://cloud.google.com/appengine/docs/standard/python/config/appref
env_variables:
  VISION_CONTAINER_ENDPOINT: "" # Fill this in when deploying.